<?php
$cardData = [ 
    [
        "header" => "6 x 25F + FC",
        "body" => "<table class='table table-striped'>
        <thead class='thead-dark'>
            <tr class='bg-dark text-light'>
                <td class='text-light w-25 text-center'>
                    Imagen
                </td>
                <td>
                    <span>∅</span>
                    (m.m)
                </td>
                <td>
                    Peso 100 m
                    (Kg/m)
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.770 N/mm<span>2</span>
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.960 N/mm<span>2</span>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan='100'>
                    <div class='d-flex justify-content-center rounded overflow-hidden'>
                        <img src='img/products/FC6x25F.jpg' width='100%' alt=''>
                    </div>
                </td>
            </tr>
                <td>
                    6
                </td>
                <td>
                    12.90
                </td>
                <td>
                    2.143
                </td>
                <td>
                    2.374
                </td>
            </tr>
            <tr>
                <td>
                    7
                </td>
                <td>
                    17.60
                </td>
                <td>
                    2.918
                </td>
                <td>
                    3.231
                </td>
            </tr>
            <tr>
                <td>
                    8
                </td>
                <td>
                    23.00
                </td>
                <td>
                    3.811
                </td>
                <td>
                    4.220
                </td>
            </tr>
            <tr>
                <td>
                    9
                </td>
                <td>
                    29.10
                </td>
                <td>
                    4.823
                </td>
                <td>
                    5.341
                </td>
            </tr>
            <tr>
                <td>
                    10
                </td>
                <td>
                    35.90
                </td>
                <td>
                    5.954
                </td>
                <td>
                    6.593
                </td>
            </tr>
            <tr>
                <td>
                    11
                </td>
                <td>
                    43.30
                </td>
                <td>
                    7.204
                </td>
                <td>
                    7.978
                </td>
            </tr>
            <tr>
                <td>
                    12
                </td>
                <td>
                    51.70
                </td>
                <td>
                    8.574
                </td>
                <td>
                    9.494
                </td>
            </tr>
            <tr>
                <td>
                    13
                </td>
                <td>
                    60.70
                </td>
                <td>
                    10.062
                </td>
                <td>
                    11.143
                </td>
            </tr>
            <tr>
                <td>
                    14
                </td>
                <td>
                    70.40
                </td>
                <td>
                    11.670
                </td>
                <td>
                    12.923
                </td>
            </tr>
            <tr>
                <td>
                    16
                </td>
                <td>
                    91.90
                </td>
                <td>
                    15.243
                </td>
                <td>
                    16.879
                </td>
            </tr>
            <tr>
                <td>
                    18
                </td>
                <td>
                    116.00
                </td>
                <td>
                    19.291
                </td>
                <td>
                    21.362
                </td>
            </tr>
            <tr>
                <td>
                    19
                </td>
                <td>
                    129.24
                </td>
                <td>
                    21.494
                </td>
                <td>
                    23.802
                </td>
            </tr>
            <tr>
                <td>
                    20
                </td>
                <td>
                    144.00
                </td>
                <td>
                    23.817
                </td>
                <td>
                    26.373
                </td>
            </tr>
            <tr>
                <td>
                    22
                </td>
                <td>
                    174.00
                </td>
                <td>
                    28.818
                </td>
                <td>
                    31.911
                </td>
            </tr>
        </tbody>
    </table>"
    ],
    [
        "header" => "Banana-tableContent",
        "body" => "<div class='bg-warning'>Banana-tableContent</div>",
    ],
    [
        "header" => "Orange-tableContent",
        "body" => "<div class='bg-success'>Orange-tableContent</div>",
    ]
];