<?php
$routeIMG = "https://ingecables-backend-production.up.railway.app/img";
$cardData = [ 
    [
        "header" => "6 x 25F + FC",
        "body" => "<table class='table table-striped'>
        <thead class='thead-dark'>
            <tr class='bg-dark text-light'>
                <td class='text-light w-25 text-center'>
                    Imagen
                </td>
                <td>
                    <span>∅</span>
                    (m.m)
                </td>
                <td>
                    Peso 100 m
                    (Kg/m)
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.770 N/mm<span>2</span>
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.960 N/mm<span>2</span>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan='100'>
                    <div class='d-flex justify-content-center rounded overflow-hidden'>
                        <img src='$routeIMG/FC6x25F.jpg' width='100%' alt=''>
                    </div>
                </td>
            </tr>
                <td>
                    6
                </td>
                <td>
                    12.90
                </td>
                <td>
                    2.143
                </td>
                <td>
                    2.374
                </td>
            </tr>
            <tr>
                <td>
                    7
                </td>
                <td>
                    17.60
                </td>
                <td>
                    2.918
                </td>
                <td>
                    3.231
                </td>
            </tr>
            <tr>
                <td>
                    8
                </td>
                <td>
                    23.00
                </td>
                <td>
                    3.811
                </td>
                <td>
                    4.220
                </td>
            </tr>
            <tr>
                <td>
                    9
                </td>
                <td>
                    29.10
                </td>
                <td>
                    4.823
                </td>
                <td>
                    5.341
                </td>
            </tr>
            <tr>
                <td>
                    10
                </td>
                <td>
                    35.90
                </td>
                <td>
                    5.954
                </td>
                <td>
                    6.593
                </td>
            </tr>
            <tr>
                <td>
                    11
                </td>
                <td>
                    43.30
                </td>
                <td>
                    7.204
                </td>
                <td>
                    7.978
                </td>
            </tr>
            <tr>
                <td>
                    12
                </td>
                <td>
                    51.70
                </td>
                <td>
                    8.574
                </td>
                <td>
                    9.494
                </td>
            </tr>
            <tr>
                <td>
                    13
                </td>
                <td>
                    60.70
                </td>
                <td>
                    10.062
                </td>
                <td>
                    11.143
                </td>
            </tr>
            <tr>
                <td>
                    14
                </td>
                <td>
                    70.40
                </td>
                <td>
                    11.670
                </td>
                <td>
                    12.923
                </td>
            </tr>
            <tr>
                <td>
                    16
                </td>
                <td>
                    91.90
                </td>
                <td>
                    15.243
                </td>
                <td>
                    16.879
                </td>
            </tr>
            <tr>
                <td>
                    18
                </td>
                <td>
                    116.00
                </td>
                <td>
                    19.291
                </td>
                <td>
                    21.362
                </td>
            </tr>
            <tr>
                <td>
                    19
                </td>
                <td>
                    129.24
                </td>
                <td>
                    21.494
                </td>
                <td>
                    23.802
                </td>
            </tr>
            <tr>
                <td>
                    20
                </td>
                <td>
                    144.00
                </td>
                <td>
                    23.817
                </td>
                <td>
                    26.373
                </td>
            </tr>
            <tr>
                <td>
                    22
                </td>
                <td>
                    174.00
                </td>
                <td>
                    28.818
                </td>
                <td>
                    31.911
                </td>
            </tr>
        </tbody>
    </table>"
    ],
    [
        "header" => "6 x 25F + IWRC",
        "body" => "<table class='table table-striped'>
        <thead class='thead-dark'>
            <tr class='bg-dark text-light'>
                <td class='text-light w-25 text-center'>
                    Imagen
                </td>
                <td>
                    <span>∅</span>
                    (m.m)
                </td>
                <td>
                    Peso 100 m
                    (Kg/m)
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.770 N/mm<span>2</span>
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.960 N/mm<span>2</span>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan='100'>
                    <div class='d-flex justify-content-center rounded overflow-hidden'>
                        <img src='$routeIMG/IWRC6x25F.jpg' width='100%' alt=''>
                    </div>
                </td>                    
                <tr>
                    <td>
                        6
                    </td>
                    <td>
                        14.40
                    </td>
                    <td>
                        2.312
                    </td>
                    <td>
                        2.561
                    </td>
                </tr>
                <tr>
                    <td>
                        7
                    </td>
                    <td>
                        19.60
                    </td>
                    <td>
                        3.147
                    </td>
                    <td>
                        3.585
                    </td>
                </tr>
                <tr>
                    <td>
                        8
                    </td>
                    <td>
                        25.60
                    </td>
                    <td>
                        4.111
                    </td>
                    <td>
                        4.552
                    </td>
                </tr>
                <tr>
                    <td>
                        9
                    </td>
                    <td>
                        32.40
                    </td>
                    <td>
                        5.203
                    </td>
                    <td>
                        5.761
                    </td>
                </tr>
                <tr>
                    <td>
                        10
                    </td>
                    <td>
                        40.00
                    </td>
                    <td>
                        6.423
                    </td>
                    <td>
                        7.113
                    </td>
                </tr>
                <tr>
                    <td>
                        11
                    </td>
                    <td>
                        48.40
                    </td>
                    <td>
                        7.772
                    </td>
                    <td>
                        8.606
                    </td>
                </tr>
                <tr>
                    <td>
                        12
                    </td>
                    <td>
                        57.60
                    </td>
                    <td>
                        9.249
                    </td>
                    <td>
                        10.242
                    </td>
                </tr>
                <tr>
                    <td>
                        13
                    </td>
                    <td>
                        67.60
                    </td>
                    <td>
                        10.855
                    </td>
                    <td>
                        12.021
                    </td>
                </tr>
                <tr>
                    <td>
                        14
                    </td>
                    <td>
                        78.40
                    </td>
                    <td>
                        12.590
                    </td>
                    <td>
                        13.941
                    </td>
                </tr>
                <tr>
                    <td>
                        16
                    </td>
                    <td>
                        102.00
                    </td>
                    <td>
                        16.443
                    </td>
                    <td>
                        18.209
                    </td>
                </tr>
                <tr>
                    <td>
                        18
                    </td>
                    <td>
                        130.00
                    </td>
                    <td>
                        20.811
                    </td>
                    <td>
                        23.045
                    </td>
                </tr>
                <tr>
                    <td>
                        19
                    </td>
                    <td>
                        144.00
                    </td>
                    <td>
                        23.188
                    </td>
                    <td>
                        25.677
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        160.00
                    </td>
                    <td>
                        25.693
                    </td>
                    <td>
                        28.451
                    </td>
                </tr>
                <tr>
                    <td>
                        22
                    </td>
                    <td>
                        194.00
                    </td>
                    <td>
                        31.088
                    </td>
                    <td>
                        34.426
                    </td>
                </tr>
            </tbody>
        </table>"
    ],
    [
        "header" => "6 x 36 + IWRC Compactado",
        "body" => "<table class='table table-striped'>
        <thead class='thead-dark'>
            <tr class='bg-dark text-light'>
                <td class='text-light w-25 text-center'>
                    Imagen
                </td>
                <td>
                    <span>∅</span>
                    (m.m)
                </td>
                <td>
                    Peso Aprox.
                    (Kg/m)
                </td>
                <td>
                    Carga de rotura
                    Min. (kg) 1.960 N/mm<span>2</span>
                </td>
            </tr>
        </thead>
        <tbody>
            <td rowspan='100'>
                <div class='d-flex justify-content-center rounded overflow-hidden'>
                    <img src='$routeIMG/IWRC6x36COMP.jpg' width='100%' alt=''>
                </div>
            </td> 
            <tr>
                <td>
                    14
                </td>
                <td>
                    0.89
                </td>
                <td>
                    17.210
                </td>
            </tr>
            <tr>
                <td>
                    16
                </td>
                <td>
                    1.16
                </td>
                <td>
                    21.117
                </td>
            </tr>
            <tr>
                <td>
                    18
                </td>
                <td>
                    1.47
                </td>
                <td>
                    26.727
                </td>
            </tr>
            <tr>
                <td>
                    20
                </td>
                <td>
                    1.82
                </td>
                <td>
                    32.994
                </td>
            </tr>
            <tr>
                <td>
                    22
                </td>
                <td>
                    2.20
                </td>
                <td>
                    40.010
                </td>
            </tr>
            <tr>
                <td>
                    24
                </td>
                <td>
                    2.62
                </td>
                <td>
                    47.517
                </td>
            </tr>
            <tr>
                <td>
                    26
                </td>
                <td>
                    3.07
                </td>
                <td>
                    55.764
                </td>
            </tr>
            <tr>
                <td>
                    28
                </td>
                <td>
                    3.56
                </td>
                <td>
                    63.753
                </td>
            </tr>
            <tr>
                <td>
                    30
                </td>
                <td>
                    4.09
                </td>
                <td>
                    74.246
                </td>
            </tr>
            <tr>
                <td>
                    32
                </td>
                <td>
                    4.65
                </td>
                <td>
                    84.472
                </td>
            </tr>
            <tr>
                <td>
                    34
                </td>
                <td>
                    5.25
                </td>
                <td>
                    95.364
                </td>
            </tr>
            <tr>
                <td>
                    36
                </td>
                <td>
                    5.89
                </td>
                <td>
                    104.327
                </td>
            </tr>
        </tbody>
        </table>"
    ]    
];